"""Browser checks for existing secondary controls; no new product behavior."""
import re
from playwright.sync_api import expect

def run(page, context, base, api, check):
    prompt=page.get_by_role('dialog',name='Add Heritage Tourism Planner to Home Screen',exact=True)
    if not page.evaluate("localStorage.getItem('heritage_pwa_prompt_dismissed_v1')"):
        expect(prompt).to_be_visible(timeout=5000)
        prompt.get_by_role('button',name='Maybe Later',exact=True).click()
        expect(prompt).to_have_count(0)
        page.wait_for_timeout(1500)
        expect(prompt).to_have_count(0)
        check('Existing PWA prompt dismissal persists')
    page.get_by_role('button', name='View Mode: Tourist', exact=True).click()
    expect(page.get_by_text('Your role is supplied by the authenticated server account.', exact=True)).to_be_visible()
    page.get_by_role('button', name='Save Account Changes', exact=True).click()
    expect(page.get_by_text('Account editing is not available from the API yet. No changes were saved.', exact=True)).to_be_visible()
    check('Profile role and account-save controls honestly report backend capabilities')
    ids=page.evaluate("JSON.parse(sessionStorage.getItem('heritage_api_trip_ids'))")
    page.get_by_role('button', name='Remove', exact=True).first.click()
    remaining=page.evaluate("JSON.parse(sessionStorage.getItem('heritage_api_trip_ids'))")
    assert len(remaining)==len(ids)-1
    removed=next(i for i in ids if i not in remaining)
    token=page.evaluate("sessionStorage.getItem('heritage_api_token')")
    assert context.request.get(api+'/trips/'+removed,headers={'Authorization':'Bearer '+token}).status==200
    check('Profile Remove changes session history and preserves persisted trip')
    page.get_by_role('button', name='Open Itinerary', exact=True).first.click()
    page.wait_for_url('**/itinerary')
    # Wait for the exiting profile before interacting with the new route.
    expect(page.get_by_role('button', name='Open Itinerary', exact=True)).to_have_count(0)
    page.get_by_role('button', name='View budget breakdown', exact=True).click()
    page.wait_for_url('**/budget')
    expect(page.get_by_role('heading', name=re.compile('Heritage Budget Ledger'))).to_be_visible()
    expect(page.get_by_text('Unknown (excluded)',exact=True)).to_be_visible()
    original=page.locator('input[type=number]').input_value()
    page.locator('input[type=number]').fill('12345')
    expect(page.get_by_text('Use Adjust Trip Parameters to save a new budget.',exact=True)).to_be_visible()
    expect(page.locator('input[type=number]')).to_have_value(original)
    for label in ['Stay Saver','Book Online ASI Combination Ticket','GSRTC Volvo Bus for Inter-City Legs']:
        page.get_by_role('button',name=re.compile(re.escape(label))).click()
        expect(page.get_by_text('The ledger shows saved costs. Change trip parameters in the planner to generate a new budget.',exact=True)).to_be_visible()
    page.evaluate("() => { navigator.share=undefined; window.copyBefore=navigator.clipboard.writeText.bind(navigator.clipboard); navigator.clipboard.writeText=async()=>{throw Error('Denied test')}; }")
    page.get_by_role('button',name='Share Ledger',exact=True).click()
    expect(page.get_by_text('Unable to share the budget. Copy the page address manually.',exact=True)).to_be_visible()
    page.evaluate('() => { navigator.clipboard.writeText=window.copyBefore; }')
    check('Budget target and all savings controls preserve server totals; failed sharing is visible')
    page.get_by_role('button',name='Adjust Trip Parameters',exact=True).click()
    page.get_by_role('button',name='Continue to Logistics',exact=True).click()
    days=page.locator('#planner-trip-days').inner_text()
    page.get_by_role('button',name='Decrease trip duration',exact=True).click()
    page.get_by_role('button',name='Increase trip duration',exact=True).click()
    expect(page.locator('#planner-trip-days')).to_have_text(days)
    page.locator('#planner-start-time').select_option('09:00 AM')
    page.locator('#planner-start-time').select_option('08:00 AM')
    page.get_by_role('button',name='Review Plan',exact=True).click()
    page.get_by_role('button',name='Adjust Logistics',exact=True).click()
    page.get_by_role('button',name='Review Plan',exact=True).click()
    page.get_by_role('button',name='Compare optimization strategies',exact=True).click()
    expect(page.get_by_role('button',name='Use this plan',exact=True)).to_have_count(3)
    stats=page.locator('[aria-labelledby=strategy-comparison-title]').get_by_role('button',name='Toggle algorithm stats detail',exact=True).first
    stats.click()
    expect(stats).to_have_attribute('aria-expanded','true')
    stats.click()
    expect(stats).to_have_attribute('aria-expanded','false')
    for _ in range(3): page.get_by_role('button',name='Collapse',exact=True).first.click()
    expect(page.get_by_role('button',name='Expand',exact=True)).to_have_count(3)
    for _ in range(3): page.get_by_role('button',name='Expand',exact=True).first.click()
    expect(page.get_by_role('button',name='Collapse',exact=True)).to_have_count(3)
    page.set_viewport_size({'width':390,'height':844})
    comparison=page.locator('[aria-labelledby=strategy-comparison-title]')
    for label in ['Budget-first','Rating-first','Distance-first']:
        tab=comparison.get_by_role('button',name=re.compile('^'+label))
        tab.scroll_into_view_if_needed()
        expect(tab).to_be_in_viewport()
        tab.click()
        expect(tab).to_have_class(re.compile('bg-ink text-gold'))
        expect(comparison.get_by_role('heading',name=label,exact=True)).to_be_visible()
        # Wait for the selected tab's real CSS transition before a new click/reflow.
        # Native pointer checks remain enabled; never force or synthesize the click.
        page.wait_for_function('(button) => button.getAnimations().every(a => a.playState !== "running")',arg=tab.element_handle())
    page.set_viewport_size({'width':1280,'height':900})
    page.get_by_role('button',name='Use this plan',exact=True).first.click()
    expect(page.get_by_text('Base Hotel:',exact=False).first).to_be_visible()
    page.reload()
    expect(page.get_by_text('Base Hotel:',exact=False).first).to_be_visible()
    check('Strategy comparison generates three server plans; expansion, mobile tabs and Use this plan persist')
    for language in ['Hindi','English']:
        page.get_by_role('button',name='Switch to '+language,exact=True).first.click()
        expect(page.get_by_role('button',name='Switch to '+language,exact=True).first).to_have_attribute('aria-pressed','true')
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('button',name='Toggle navigation menu',exact=True).click()
    page.get_by_role('button',name='Explore',exact=True).last.click()
    expect(page.get_by_role('button',name='Toggle navigation menu',exact=True)).to_have_attribute('aria-expanded','false')
    page.set_viewport_size({'width':1280,'height':900})
    check('All language toggles and responsive navigation drawer')
    for label,slug in [('White Rann & Kutch','rann-of-kutch'),('Sacred Saurashtra','somnath'),('UNESCO Citadel Circuit','champaner')]:
        page.get_by_role('button',name=label,exact=True).click()
        page.wait_for_url('**/destination/'+slug)
    for label in ['Solanki Stepwells','Ticket Fee Ledgers','Craft Village Guild Directory']:
        page.get_by_role('button',name=label,exact=True).click()
        expect(page.get_by_placeholder('Search destinations or districts...')).to_be_visible()
    page.get_by_role('button',name='Heritage Haveli Lodging',exact=True).click()
    expect(page.get_by_role('button',name='Lowest Price',exact=True)).to_be_visible()
    page.get_by_role('button',name='View City Overview →',exact=True).click()
    expect(page.get_by_role('button',name='Build Custom Itinerary',exact=True)).to_be_visible()
    check('All footer circuit/directory/lodging links and hotel city overview')
    for label in ['Terrace Itinerary Generator']:
        page.get_by_role('button',name=label,exact=True).click()
        expect(page.get_by_role('button',name='Close trip planner',exact=True)).to_be_visible()
        page.get_by_role('button',name='Close trip planner',exact=True).click()
    page.locator('nav').get_by_text('Gujarat Heritage Directory',exact=True).click()
    page.get_by_role('button',name=re.compile('^Start planning$',re.I)).click()
    page.keyboard.press('Escape')
    page.get_by_role('button',name=re.compile('^Browse .* Heritage Sites$',re.I)).click()
    expect(page.get_by_placeholder('Search destinations or districts...')).to_be_visible()
    check('Hero planning/browsing, footer planner and modal close controls')
    for label in ['Return to Home','Explore Monuments','Ranked Stays']:
        page.goto(base+'/nonexistent-completion-route')
        page.get_by_role('button',name=label,exact=True).last.click()
        assert 'nonexistent-completion-route' not in page.url
    for label in ['Browse Destinations','Plan New Itinerary','Return to Home Screen']:
        page.goto(base+'/?shared=bad-payload')
        expect(page.get_by_text('Invalid Shared Itinerary Link',exact=True)).to_be_visible()
        page.get_by_role('button',name=label,exact=True).click()
        assert 'shared=' not in page.url
    check('Not-found and invalid-shared-link recovery buttons')
